### ISSUE TITLE
Is it possible to merge several knowledge bases in a new one?

### ISSUE THREAD

**Issue by saucisson** [kyouko-taiga/LogicKit#1]
This seems to be useful for modularity.

**Comment by kyouko-taiga** [comment]
Knowledge bases simply wrap an array that you can manipulate with Swift's standard methods. For instance:

```swift
let kb2 = KnowledgeBase(knowledge: kb1.knowledge + [ some, additional, clauses ])
```

For convenience, 2306c68661add8d95de9c42848dd2425ef48377a adds a `union(_:)` method:

```swift
let kb2 = kb1.union(with: [ some, additional, clauses ])
```
