### ISSUE TITLE
Arm compilation

### ISSUE THREAD

**Issue by panos2310gr** [kyouko-taiga/LogicKit#16]
Is there a way to get LogicKit to compile for Arm? 
I get:
Could not find module 'LogicKit' for target 'arm64-apple-macos'; found: x86_64, x86_64-apple-macos

**Comment by kyouko-taiga** [comment]
There shouldn't be any particular reason preventing LogicKit to run on ARM. I is written in pure Swift and, as best as I can remember, does not depend on any x86-specific thing.

Did you try to re-compile it from sources?

**Comment by panos2310gr** [comment]
The library is declared as a swift package (the git url is entered). 
This is the way to download and compile from source (are there binaries available at all?)

Regards.

**Comment by panos2310gr** [comment]
Ok, found the solution here:

https://developer.apple.com/forums/thread/667440 <https://developer.apple.com/forums/thread/667440>

It was an Xcode settings issue!

Thanks.

**Comment by kyouko-taiga** [comment]
No worries!
