### ISSUE TITLE
Method to count the number of terms within a rule stage

### ISSUE THREAD

**Issue by panos2310gr** [kyouko-taiga/LogicKit#17]
Hi I am trying to build a term that returns true if the number of results is above a specific number:

  let success = Term.rule("success") {
        .fact("action", "s93663", .var("date"), .var("number1"), .var("number2"))
            &&  List.count(list: (List.from(elements: .var("date")) , count: .var("count"))
            &&  Nat.greaterOrEqual(  .var("count") , Nat.from(3))
    }

I want to be able to count the instances of "date" in my set.

I know that it would be possible to count the items in the answerset in swift but I want to reuse the rule in other rules and I would like to be able to solve with LogicKit only.

**Comment by kyouko-taiga** [comment]
I'm afraid you can't do this with LogicKit only. One design principle is precisely to avoid implementing Prolog's meta-operators within the logic language.

Is there any specific reason why you don't want to count the number of results outside of LogicKit?

**Comment by panos2310gr** [comment]
Thanks, is there a way to get this info with a comparison in a “native” type of term?

Could you give an example of a similar syntax of native terms?

I want to use the number of results to feed them to another rule, that gives dynamically updated results.

**Comment by kyouko-taiga** [comment]
If you take the introductory example from the readme, you can count the number of results by enumerating the answer set. This will give you a `Swift.Int` value that you can feed back in a dynamically generated knowledge base:

```swift
// ...
var answers = staticKB.ask(.fact("is stronger", .var("a"), .var("b")))
let count = Array(answers).count
let dynamicKB: KnowledgeBase = staticKB + [
  .fact("someNewFact", Nat.from(count)),
]
```

`dynamicKB` will contain all the facts and rules from `staticKB`, plus a new fact generated dynamically from the result of a request.

Note that this won't work if LogicKit is unable to enumerate all results. So you need to make sure it is able to compute the exhaustive set of answers to a specific request.

**Comment by panos2310gr** [comment]
Thanks. 

Could this be done with the experimental native type if term?

**Comment by kyouko-taiga** [comment]
Well, you can capture `count` in the closure of a native predicate. But that will be more complex and less efficient than creating a regular predicate.

```swift
// ...
let count = Array(answers).count
let dynamicKB: KnowledgeBase = staticKB + [
  .native({ t in t["x"]! == Nat.from(count) })
]
```

Native predicates are designed to handle cases where you can't get away with term equality (e.g., because you want to use Swift's subtyping).

**Comment by panos2310gr** [comment]
Thanks. Still, there is need for a clause outside of LogicKit.

I would like to be able to capture the count without having to actually ask for an answer.

To help you understand the purpose of my application:

There is a database in place which is accessed and a set of facts are added to a Knowledgebase from the contents of the database.

In addition I am describing a set of rules that combine the facts to present some results. 

I want to be able to design the ruleset without having to resort to swift code, otherwise I could do it with a set of if/then/else and case clauses.

I need the logic programming to be a separate independent part of my app.

**Comment by kyouko-taiga** [comment]
Unless requests are issued dynamically to your knowledge base (and even then you could probably create new KBs dynamically in the request handler), there is no reason why you couldn't emit Swift code in response to what goes into your knowledge base.

**Comment by panos2310gr** [comment]
Thank you very much.

Are there any plans to update/evolve LogicKit?

**Comment by kyouko-taiga** [comment]
I haven't planned any significant update at the moment, but I am open to extend LogicKit with new features.
And of course, I plan to maintain the library to fix bug or migrate to new versions of Swift.

**Comment by panos2310gr** [comment]
keep up the good work
