### ISSUE TITLE
[Question] Syntax help

### ISSUE THREAD

**Issue by maxeeem** [kyouko-taiga/LogicKit#19]
I'm new to Prolog and i'm trying to convert some statements from an existing script using LogicKit. 

This rule definition works in SWI-Prolog
`inference(inheritance(M, P), inheritance(S, M), inheritance(S, P)) :- S \= P.`
And when ask the system a question 
`inference(inheritance(bird, animal), inheritance(robin, bird), T).`
It correctly responds with 
`T = inheritance(robin,animal)`

I've tried a few different combinations but couldn't get even this simple case to work in LogicKit. As i said, I'm really new to Prolog so I must be missing something here. For one, I don't know how to express `S \= P` in LogicKit which I suspect is why I can't get it to work. It should be something like  `not ( Term.var("S") ~=~ Term.var("P") )` but I couldn't figure out how to express this. 

Thanks!

This is what I have so far
```
let kb: KnowledgeBase = [
        .rule("inference", 
            .fact("inheritance", "M", "P"),
            .fact("inheritance", "S", "M"),
            .fact("inheritance", "S", "P")) { 
                  //
                  // what should go here???
                  //
            }
    ]
    
    let results = 
          kb.ask(
            .fact("inference", 
                .fact("inheritance", "bird", "animal"),
                .fact("inheritance", "robin", "bird"),
                .var("result"))
        )

    print(results)
```

**Comment by kyouko-taiga** [comment]
LogicKit is a prolog-like DSL but it is not prolog. In particular, it cannot express negation the same way. So you can't express `S \= P` as a premise.

I guess you could use a native predicate to that effect.

**Comment by maxeeem** [comment]
Thank you for the reply. It makes sense now.
